document.addEventListener('DOMContentLoaded', function () {

    // Function to generate a random customer ID (between 100 and 9999)
    function generateCustomerId() {
        return Math.floor(Math.random() * (9999 - 100 + 1)) + 100;
    }

    // Function to handle checkout submission
    function handleCheckout(event) {
        event.preventDefault(); // Prevent form submission

        // Generate a random customer ID and the current date for order_date
        const customerId = generateCustomerId();
        const orderDate = new Date().toISOString(); // Get current date in ISO 8601 format

        // Get other data from the form
        const totalAmount = document.getElementById('total_amount').value;
        const paymentMethod = document.getElementById('payment_method').value;
        const shippingAddress = document.getElementById('shipping_address').value;

        // Create order object
        const orderData = {
            order_id: null, // order_id will be generated by backend
            customer_id: customerId,
            order_date: orderDate,
            total_amount: totalAmount,
            payment_method: paymentMethod,
            shipping_address: shippingAddress,
        };

        // Display the order summary
        displayOrderSummary(orderData);
    }

    // Function to display the order summary
    function displayOrderSummary(orderData) {
        const summaryDiv = document.getElementById('order-summary');
        
        summaryDiv.innerHTML = `
            <h3>Order Summary</h3>
            <p><strong>Customer ID:</strong> ${orderData.customer_id}</p>
            <p><strong>Order Date:</strong> ${orderData.order_date}</p>
            <p><strong>Total Amount:</strong> $${orderData.total_amount}</p>
            <p><strong>Payment Method:</strong> ${orderData.payment_method}</p>
            <p><strong>Shipping Address:</strong> ${orderData.shipping_address}</p>
        `;
        
        // Show the order summary section
        summaryDiv.style.display = 'block';
    }

    // Add event listener for form submission
    const form = document.getElementById('checkout-form');
    form.addEventListener('submit', handleCheckout);
});
